version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: apis
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: apis

	apis:
		build: .
		image: chamaconekt/apis
		links:
		- postgres
		container_name: apis
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- apis
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/apis-nginx/nginx.conf
		depends_on:
			- apis
		ports:
			- 80:80
		volumes_from:
			- apis

volumes:
	apis-static-files:
		driver:local